environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python installs, check which one used by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Install globally (pyinstaller v3.2 has VC++ redistributable dependencies)
  - cmd: pip install pyinstaller==3.1.1
  - cmd: python setup.py install
  - cmd: pip freeze

  # Build using PyInstaller, rename dist folder
  - cmd: pyinstaller package\pyinstaller-cli.spec
  - cmd: pyinstaller package\pyinstaller-gui.spec
  - ps: Rename-Item -path .\dist artifacts
  - cmd: dir artifacts

  # Install with Pipenv so that we can run the tests
  - cmd: pip install pipenv
  - cmd: pipenv install --dev .
  - cmd: pipenv run pip freeze

  # Prepare codecov coverage
  - cmd: pip install codecov

test_script:
  - cmd: pipenv run flake8 ubitflashtool/ tests/
  - cmd: pipenv run python -m pytest -v --cov=ubitflashtool tests/
  # Lastly just run it as a simple test to check ubitflashtool is not broken
  - cmd: .\artifacts\ubitflashtool-cli.exe --help

after_test:
  # Create AppVeyor artifact to be uploaded
  - ps: Push-AppveyorArtifact .\artifacts\ubitflashtool-gui.exe
  - ps: Push-AppveyorArtifact .\artifacts\ubitflashtool-cli.exe

  # Upload test coverage report
  - cmd: codecov

# Not a project with an msbuild file, build done at install.
build: None
