environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.10"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python install, check which one uses by default
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Install python dependencies (v3.2 has VC++ redistributable dependencies)
  - cmd: pip install pyinstaller==3.1.1
  - cmd: python setup.py install

  # Check installed packages
  - cmd: pip freeze

  # Build mu using PyInstaller, rename dist folder
  - cmd: pyinstaller ubitextract\gui.py --onefile --name ubitextract-gui
  - ps: Rename-Item -path .\dist artifacts
  - cmd: dir artifacts

  # Create AppVeyor artifact
  - ps: Push-AppveyorArtifact .\artifacts\ubitextract-gui.exe

# Not a project with an msbuild file, build done at install.
build: None
