environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

platform: x86

configuration: Release

init:
  - cmd: ver
  - cmd: ECHO Processor architecture - %PROCESSOR_ARCHITECTURE%
  - cmd: wmic OS get OSArchitecture

  # As AppVeyor has multiple python installs, check which one used by default
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"

  # Set the relevant Python and pip location to the path
  - cmd: ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%
  - cmd: set PATH=%PYTHON%;%PYTHON%\scripts;%PATH%
  - cmd: ECHO Path - %PATH%

  # Verify the new default python
  - cmd: python --version
  - cmd: python -c "import struct; print(struct.calcsize('P') * 8)"
  - cmd: python -c "import sys; print(sys.executable)"
  - cmd: pip --version

  # Check out installed python packages
  - cmd: pip freeze

install:
  # Install with Pipenv so that we can run the tests
  - cmd: pip install pipenv
  - cmd: pipenv install --dev . --ignore-pipfile
  - cmd: pipenv run python --version
  - cmd: pipenv run pip freeze

  # Build and rename dist folder
  - cmd: pipenv run python make.py build
  - ps: Rename-Item -path .\dist artifacts
  - cmd: dir artifacts

  # Prepare codecov coverage
  - cmd: pip install codecov

test_script:
  - cmd: pipenv run python make.py check
  # Run cli app as a simple test to check ubittool build is not broken
  - cmd: .\artifacts\ubittool-cli.exe --help

after_test:
  # Create AppVeyor artifact to be uploaded
  - ps: Push-AppveyorArtifact .\artifacts\ubittool-gui.exe
  - ps: Push-AppveyorArtifact .\artifacts\ubittool-cli.exe

  # Upload test coverage report
  - cmd: codecov

# Not a project with an msbuild file, build done at install.
build: None
