# Travis can building for OS X 10.10 Yosemite
matrix:
  include:
    - os: osx
      osx_image: xcode6.4
      sudo: required
      language: generic

before_install:
  # OS and Python info
  - uname -a
  - sudo -H python -c "import sys; print(sys.executable)"
  - curl -O https://bootstrap.pypa.io/get-pip.py && sudo -H python get-pip.py && rm get-pip.py
  - sudo -H pip --version
  - sudo -H pip freeze

install:
  - sudo -H pip install --upgrade setuptools
  - sudo -H pip install pyinstaller
  - sudo -H pip install cython
  - sudo -H pip install setuptools_scm
  - sudo -H pip install --pre -U pyocd
  #- sudo -H pip install --pre -U git+https://github.com/mbedmicro/pyOCD.git#egg=proj
  #- cd .. && git clone https://github.com/gbishop/cython-hidapi.git && cd ubitflashtool
  #- cd ../cython-hidapi && python setup-mac.py build && cd ../ubitflashtool
  #- cd ../cython-hidapi && python setup-mac.py install && cd ../ubitflashtool
  - sudo -H python setup.py install
  - sudo -H pip install .
  
  # Check things were installed correctly
  - sudo -H python -c "import hid"
  - sudo -H pip freeze

  # Build mu using PyInstaller
  - pyinstaller package/pyinstaller-cli.spec
  - pyinstaller package/pyinstaller-gui.spec
  - mv dist artifacts
  - ls -l artifacts
  - chmod +x ./artifacts/ubitflashtool-cli
  - cd artifacts && zip --symlinks -r ubitflashtool-gui.zip ubitflashtool-gui.app && cd ..

script:
  - curl --upload-file ./artifacts/ubitflashtool-gui.zip https://transfer.sh/ubitflashtool-gui.zip
  - curl --upload-file ./artifacts/ubitflashtool-cli https://transfer.sh/ubitflashtool-cli
  - ./artifacts/ubitflashtool-cli -s my_script.py


notifications:
  email:
    on_success: change
    on_failure: change
