# Tests multiple Python versions in Linux and build in macOS 
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: 3.5
    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: 3.6
    - os: linux
      dist: xenial
      sudo: false
      language: python
      python: 3.7
    # OS X 10.11 El Capitan
    - os: osx
      osx_image: xcode7.3
      sudo: required
      language: generic
      env: PY_VER=3.5.2

before_install:
  # OS info
  - uname -a
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sw_vers; fi
  # macOS needs python3 to be installed
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv install --list; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then CONFIGURE_OPTS=--enable-shared pyenv install $PY_VER; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then pyenv global $PY_VER; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ln -s `pyenv which python` /usr/local/bin/python3 ; fi
  # Python info
  - python3 --version
  - python3 -c "import struct; print(struct.calcsize('P') * 8)"
  - python3 -c "import sys; print(sys.executable)"
  - python3 -m pip --version
  - python3 -m pip freeze

install:
  # Install and check installed packages
  - python3 -m pip install pipenv
  - python3 -m pipenv install --dev .
  - python3 -m pipenv run pip freeze

  # Build the two versions of ubitflashtool in macOS using PyInstaller
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pipenv run python make.py build; fi

  # Collect the build outputs in macoOS
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo -H mv dist artifacts; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ls -l artifacts; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo -H chmod +x ./artifacts/ubitflashtool-cli; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cd artifacts && sudo -H zip --symlinks -r ubitflashtool-gui.zip ubitflashtool-gui.app && cd ..; fi

  # Prepare codecov coverage
  - python3 -m pip install codecov

script:
  # Running the tests. Linux needs frame buffer, so run with "xvfb-run".
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then xvfb-run python3 -m pipenv run python make.py check; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then python3 -m pipenv run python make.py check; fi
  # Run cli app as a simple test to check ubitflashtool build is not broken
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./artifacts/ubitflashtool-cli --help; fi

after_script:
  # Upload built executables to a temporary service
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl --upload-file ./artifacts/ubitflashtool-gui.zip https://transfer.sh/ubitflashtool-gui.zip ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then curl --upload-file ./artifacts/ubitflashtool-cli https://transfer.sh/ubitflashtool-cli ; fi
  # - curl -F "file=@./artifacts/ubitflashtool-gui.zip" "https://file.io/?expires=3"
  # - curl -F "file=@./artifacts/ubitflashtool-cli" "https://file.io/?expires=3"

  # Upload test coverage report
  - codecov

notifications:
  email:
    on_success: change
    on_failure: change
