# General Jekyll options https://jekyllrb.com/docs/configuration/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-remote-theme

# Theme and theme options
remote_theme: carlosperate/jekyll-theme-rtd
