# General Jekyll options https://jekyllrb.com/docs/configuration/
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
plugins:
  - jekyll-remote-theme
markdown:
  - kramdown

# Markdown settings: https://jekyllrb.com/docs/configuration/markdown/
kramdown:
  # GitHub flavoured markdown
  input: GFM
  # Interprets line breaks literally
  hard_wrap: false

remote_theme: carlosperate/jekyll-theme-rtd
